name: Build and Push Docker Image
description: Reusable action to build and push Docker image to GHCR

inputs:
  username:
    required: true
  token:
    required: true
  image:
    required: true
  gpr_user:
    required: false
  gpr_key:
    required: false

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      shell: bash
      run: |
        echo "${{ inputs.token }}" | docker login ghcr.io -u "${{ inputs.username }}" --password-stdin

    - name: Build and Push Image
      shell: bash
      run: |
        docker build --build-arg GITHUB_USER="${{ inputs.gpr_user }}" --build-arg GITHUB_TOKEN="${{ inputs.gpr_key }}" -t "${{ inputs.image }}" .
        docker push "${{ inputs.image }}"