name: Build and Push Docker Image
description: Reusable action to build and push Docker image to GHCR

inputs:
  username:
    required: true
  token:
    required: true
  image:
    required: true
  gpr_user:
    required: false
  gpr_key:
    required: false

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      shell: bash
      run: |
        echo "${{ inputs.token }}" | docker login ghcr.io -u "${{ inputs.username }}" --password-stdin

    - name: Build and Push Image
      shell: bash
      run: |
        CONTEXT="$GITHUB_WORKSPACE"
        DOCKERFILE="$GITHUB_WORKSPACE/Dockerfile"

        echo "Using context: $CONTEXT"
        echo "Using Dockerfile: $DOCKERFILE"

        if [ -n "${{ inputs.gpr_user }}" ] && [ -n "${{ inputs.gpr_key }}" ]; then
          docker build --no-cache \
            --build-arg GPR_USER="${{ inputs.gpr_user }}" \
            --build-arg GPR_KEY="${{ inputs.gpr_key }}" \
            -f "$DOCKERFILE" \
            -t "${{ inputs.image }}" \
            "$CONTEXT"
        else
          docker build --no-cache \
            -f "$DOCKERFILE" \
            -t "${{ inputs.image }}" \
            "$CONTEXT"
        fi

        docker push "${{ inputs.image }}"
